AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Infraestrutura automatizada simulada — demonstração prática de uso do AWS CloudFormation.
  Ele cria um bucket S3, uma instância EC2 e um grupo de segurança.

Resources:
  MeuBucketS3:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: simulacao-leh-bucket

  MeuSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Permitir acesso SSH e HTTP
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  MinhaInstanciaEC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0c02fb55956c7d316
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref MeuSecurityGroup
      Tags:
        - Key: Name
          Value: SimulacaoEC2Leh

Outputs:
  BucketName:
    Description: Nome do bucket criado
    Value: !Ref MeuBucketS3

  InstanciaID:
    Description: ID da instância EC2 criada
    Value: !Ref MinhaInstanciaEC2
